-- Add asset_assignment_history for Plant 5 assets (diesel + remisiones evidence)
-- Generated by: npm run add:plant5-history -- --from 2025-10-01 --to 2025-12-31 --sql
-- WARNING: Run only once. Re-running will create duplicate records.
-- Evidence: 48 diesel transactions at P005, 6 assets with remisiones at Planta 5 in Q4 2025
-- CF-04 excluded (new asset placed at P5 from start)

INSERT INTO asset_assignment_history (asset_id, previous_plant_id, new_plant_id, changed_by, change_reason, created_at) VALUES
  ('49234a44-1806-4042-a5c0-29513e5db3ed', NULL, 'a3e026d3-018f-43c7-8e48-f812922c90b6', 'c34258ca-cc26-409d-b541-046d53b89b21'::uuid, 'Corrección por script add-asset-assignment-history-from-plant5-evidence (diesel + remisiones P005)', '2025-11-05T23:41:00+00:00'),
  ('249cf1ff-1b2b-42fe-901c-ef122d72d768', NULL, 'a3e026d3-018f-43c7-8e48-f812922c90b6', 'c34258ca-cc26-409d-b541-046d53b89b21'::uuid, 'Corrección por script add-asset-assignment-history-from-plant5-evidence (diesel + remisiones P005)', '2025-11-10T20:28:00+00:00'),
  ('64362c6a-8533-46cc-958d-79242067fe5d', NULL, 'a3e026d3-018f-43c7-8e48-f812922c90b6', 'c34258ca-cc26-409d-b541-046d53b89b21'::uuid, 'Corrección por script add-asset-assignment-history-from-plant5-evidence (diesel + remisiones P005)', '2025-11-13T15:27:00+00:00'),
  ('001c8c0f-c3ae-4118-a94a-d83c06192b1b', 'eb050cd7-5db8-4113-9db6-849ba8af28be', 'a3e026d3-018f-43c7-8e48-f812922c90b6', 'c34258ca-cc26-409d-b541-046d53b89b21'::uuid, 'Corrección por script add-asset-assignment-history-from-plant5-evidence (diesel + remisiones P005)', '2025-12-17T12:00:00.000Z');
